### ISSUE TITLE
"Build the Docs" auto-update doc suggestion

### ISSUE THREAD

**Issue by purplediane** [twoscoops/Creating-and-Distributing-Python-Packages#10]
## Location within the Course

* Section: 3
* Lesson: 5
* Language: English

## Description 

In the section `Auto-Update Local Changes in Browser`, at the end, add "When you're done, use `CTRL-C` to exit the doc server." 

I'm on a Mac. Does `CTRL-C` work on Windows for this? If not, we should include that instruction too.

**Comment by pydanny** [comment]
Yes, ctrl-c works for this on Windows. 😄
