### ISSUE TITLE
Misspelled "seperate", s.b."separate"

### ISSUE THREAD

**Issue by purplediane** [twoscoops/Creating-and-Distributing-Python-Packages#14]
## Location within the Course

* Section: 3
* Lesson: 1
* Language:

## Description 

In "Check that your new package and virtualenv are seperate", should be "separate".

**Comment by purplediane** [comment]
Also, 2 paragraphs down there is "occured", s.b. "occurred".

**Comment by pydanny** [comment]
Resolved
