### ISSUE TITLE
Need to add .pytest_cache to .gitignore

### ISSUE THREAD

**Issue by purplediane** [twoscoops/Creating-and-Distributing-Python-Packages#16]
## Location within the Course

* Section: 4
* Lesson: 1
* Language:English

## Description 

After running pytest tests, git status shows the .pytest_cache as new files needing add/commit. I put `.pytest_cache/` in my `.gitignore` file. I think this should be mentioned.

**Comment by purplediane** [comment]
Also, should `make clean-test` remove the `.pytest_cache` directory?

**Comment by pydanny** [comment]
Resolved in https://github.com/audreyr/cookiecutter-pypackage/commit/028f38a28685488d0f240d2669813612ec2b48b4
