### ISSUE TITLE
PyUp badge is not bundle with the templates

### ISSUE THREAD

**Issue by nicoguaro** [twoscoops/Creating-and-Distributing-Python-Packages#2]
## Location within the Course

* Chapter: 4
* Section: 6
* Language: English

## Description
It says:

> Now, if you go to your project's repo on GitHub and scroll down, the pyup badge show green as seen below:

But the badge was not therein the first place.

**Comment by nicoguaro** [comment]
Change title

**Comment by cosmoscalibur** [comment]
This is because in 3.1 option was used as default `n` (#21).

**Comment by pydanny** [comment]
This has been corrected in 3.1, probably by you, @cosmoscalibur. 😄
