### ISSUE TITLE
More explanation for PyUp

### ISSUE THREAD

**Issue by purplediane** [twoscoops/Creating-and-Distributing-Python-Packages#21]
## Location within the Course

* Section:4
* Lesson:6
* Language:English

## Description 

We said no to PyUp when we ran cookiecutter. But then in 4.6, the first thing we do is PyUp. A few words would be nice explaining why we are doing that here, even though we said no to PyUp initially. 

Also, this is my concern: I can update my dependencies with the automated PR from PyUp, but now my development environment on my computer is not the same as what's in the requirements-dev.txt file. So we need to run some kind of `pip upgrade` on these things, right? We should have some discussion of that, too.

**Comment by pydanny** [comment]
Resolved by changes to 3.1 as specified in #2.
