### ISSUE TITLE
CLI section confusing

### ISSUE THREAD

**Issue by purplediane** [twoscoops/Creating-and-Distributing-Python-Packages#22]
## Location within the Course

* Section:5
* Lesson:1
* Language:English

## Description 

Cookiecutter did not make a `<project>.cli` file. It did, however, make a `cli.py` file that looks a lot like the `arepa.cli` file shown. When I added the `click` stuff, it works to call it from the command line.

The courseware should be updated to fix this this and explain what is going on.

**Comment by pydanny** [comment]
Resolved!
