### ISSUE TITLE
Sections 2.2, 2.3, 6.3 code snippets not formatted

### ISSUE THREAD

**Issue by purplediane** [twoscoops/Creating-and-Distributing-Python-Packages#26]
## Location within the Course

* Section:2
* Lesson:2
* Language:en

## Description 

In section 2.2, 2.3, and 6.3, the code snippets are not formatted like the code snippets on the other pages.

**Comment by purplediane** [comment]
In addition, many of the code snippets (all over, not just this lesson) do not have the command line prefix `$`.  Some show the virtualenv name in parentheses and some don't. The ones that do, usually show it after the `$`, but I've always seen it as being a prefix to the command-line prompt.

We should probably try for some kind of consistency here, although after about 3.1, I didn't notice it while I was doing the class; only now when going through the materials again with my editor hat on. :smile:

**Comment by pydanny** [comment]
@purplediane Should we do $ or not do $? What's your preference?

**Comment by pydanny** [comment]
@purplediane Is this still a problem in the course? The code examples look okay to me compared to other code examples.

**Comment by purplediane** [comment]
I should not have put these 2 things in the same issue. The first thing was that in some of the sections the formatting wasn't the same; as if different CSS template was used (or whatever makes the highlighting/formatting of the code snippets).

The second thing was a consistency issue and I think I would prefer that code snippets of command-line things show `(virtualenv-name) $` or just `$`, although I prefer the former. There is less potential for confusion, as sometimes the result of the command looks like maybe it is something that the user should type.

**Comment by cosmoscalibur** [comment]
Consistency in snippets was fixed by me.  
+ Use `$` in shell.  
+ Use `(virtualenv-name)` when a virtual environment is active.  
+ Use `>>>` in python interpreter.  

If any code block was omitted, you can say me.

**Comment by purplediane** [comment]
Excellent!
