### ISSUE TITLE
Grammar in installing cookiecutter

### ISSUE THREAD

**Issue by purplediane** [twoscoops/Creating-and-Distributing-Python-Packages#27]
## Location within the Course

* Section:2
* Lesson:2
* Language:en

## Description 

In the last line under "Steps", the sentence reads: "If the result is `Cookiecutter 1.6.0`, that you're ready to package." The word "that" should be "then".

**Comment by purplediane** [comment]
Also, the second line under Steps needs punctuation at the end.

**Comment by pydanny** [comment]
Merged
