### ISSUE TITLE
Redundant sentence in 3.1

### ISSUE THREAD

**Issue by purplediane** [twoscoops/Creating-and-Distributing-Python-Packages#29]
## Location within the Course

* Section:3
* Lesson:1
* Language:en

## Description 

Under "Use PyPI Deployment With Travis CI", the first 2 sentence starting with "Travis CI..." are duplicated after the code snippet of `use_pypi_deployment_with_travis [y]:`. In addition, there's a typo of "multuple".

**Comment by purplediane** [comment]
In addition, there is a paragraph "While Cookiecutter PyPackage has a feature to automate the Travis setup, it's a beta feature and not for beginners. Therefore, we ask you to leave this at the default value of 'n'."
But Cookiecutter doesn't ask about this. Perhaps the last sentence should end with "if you are asked".

**Comment by pydanny** [comment]
Resolved
