### ISSUE TITLE
Documentation in readthedocs not include automatic docs of modules.

### ISSUE THREAD

**Issue by cosmoscalibur** [twoscoops/Creating-and-Distributing-Python-Packages#31]
## Location within the Course

* Section: 3  
* Lesson: 6  
* Language: english

## Description 

Readthedocs is not building automated docs of modules because a `.gitignore` file is in `docs` directory excluding module documentation files.  
You need remove that file and addig the new files to the repo.

**Comment by pydanny** [comment]
I do not have this problem. Audrey does not have this problem. Perhaps there is another reason why the docs are failing?

**Comment by pydanny** [comment]
Also, do not remove the .gitignore file, you modify it

**Comment by cosmoscalibur** [comment]
@pydanny and @audreyr , the content of the `docs/.gitignore` file is:

    /<package-name>.rst
    /<package-name>.*.rst
    /modules.rst

Using this file, readthedocs not generate Module Index (and related pages).  
In case of edit this file, what line is required to remove?

**Comment by purplediane** [comment]
I think this is related to https://github.com/audreyr/cookiecutter-pypackage/issues/342

**Comment by pydanny** [comment]
Resolved
