### ISSUE TITLE
Git commit after CLI

### ISSUE THREAD

**Issue by nicoguaro** [twoscoops/Creating-and-Distributing-Python-Packages#4]
## Location within the Course

* Section: 5
* Lesson: 1
* Language: English

## Description 

It would be useful to add a the snippet for git commit and push afterwards … since it has been done during the whole material.

**Comment by purplediane** [comment]
Somewhere at the end of Section 5 we should do the commit/push and then another bumpversion. Since the section is named "Your third release".

**Comment by pydanny** [comment]
Done! Will be reflected in course material soon.
