### ISSUE TITLE
Add git and git config for new users

### ISSUE THREAD

**Issue by pydanny** [twoscoops/Creating-and-Distributing-Python-Packages#5]
## Location within the Course

* Section: 2
* Lesson: 1
* Language: both

## Description 

1. Users should be directed to check for git
2. Users should install git if necessary
3. Set git config per:

```
$ git config --global user.name "John Doe"
$ git config --global user.email johndoe@example.com
```

**Comment by purplediane** [comment]
In addition it isn't 100% clear what directory to be in when doing `git init`. The overall packaging directory, or the <project> directory...

**Comment by pydanny** [comment]
Mostly resolved

**Comment by pydanny** [comment]
Entirely resolved.
