### ISSUE TITLE
Documentation amendment about "make docs" and readthedocs

### ISSUE THREAD

**Issue by manikos** [twoscoops/Creating-and-Distributing-Python-Packages#9]
## Location within the Course

* Section: 3
* Lesson: 5
* Language: en

## Description 

Better add to this section that after `make docs`, the generated docs will **not** appear online on `readthedocs.org`. Only locally. 

Because the user/student expects that once the building of the docs complete, they'll be uploaded to the `readthedocs` website. This is happening on Section 5, lesson 2, actually.

**Comment by purplediane** [comment]
Yes, at the end of 5.2, we could have something like: "Click the down-arrow next to your username and select `My Projects`. Readthedocs will build your documentation and the page will say 'Your documentation is ready' when it is finished. Click the button that says 'View your documentation' to see your package's documentation on readthedocs.io."

**Comment by pydanny** [comment]
Resolved by adding @purplediane's comment to the end of 5.2
